version: "3.7"

## this running with single node
services:
  minio:
    image: minio/minio:RELEASE.2021-10-27T16-29-42Z
    hostname: minio
    volumes:
      - data_minio:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: warga

    ## new minio version command
    command: server --address ":9001" --console-address ":9002" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9001:9001"
      - "9002:9002"

volumes:
  data_minio:
    external: true
