on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Push to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${DOCKERHUB_USERNAME}
          password: ${DOCKERHUB_PASSWORD}


      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${DOCKERHUB_ACCOUNT}/${DOCKERHUB_IMAGE}:latest


      //hit endpoint to update service with new image
      - name: curl
        uses: wei/curl@master
        with:
          args: -X POST ${PORTAINER_SERVICE_URL}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
