version: "3"

services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.4
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api"
      - "--api.dashboard=true"

      ## providers
      - "--providers.docker"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.network=traefik-public"

      ## entrypoints can using
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.postgresql.address=:5432"

      ## certificates
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL_NOTICE}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--accesslog=true"
      - "--log.level=DEBUG"
    deploy:
      labels:
        
        - "traefik.enable=true"

        ## routers 
        - "traefik.http.routers.dashboard.rule=Host(`${DOMAIN_TRAEFIK}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
        - "traefik.http.routers.dashboard.service=api@internal"

        ## using middlewares in api to secure
        - "traefik.http.routers.api.middlewares=auth"

        ## dummy
        - "traefik.http.services.dummy-svc.loadbalancer.server.port=9999"

        ## middleware
        - "traefik.http.middlewares.auth.basicauth.users=ad:$$apr1$$WYs13GYf$$0eg0OF63J1DjaXigkjfRQ0"
    ports:
      # The HTTP port
      - "80:80"
      - "5432:5432"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      #- "8080:8080"
    networks:
      - traefik-public
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-acme-json:/letsencrypt

volumes:
  traefik-acme-json:

networks:
  //create network manual
  traefik-public:
    external: true
